Fix HLS Bug and assertions on wl, also adjust instr encoding
EECS-NTNU/bismo pull request #7
Opened 2019-09-13 14:24 UTC by kathjo

The commits up to a0a5ce6a... are firstly a fix of the io_sections in the FetchInstrGen to avoid the warning "Protocol 'io_section' contains conflicting I/O accesses" when synthesizing HLS. 
And secondly there is a fix for the assertion on the size of the fetch-instruction section called "dram_block_size_bytes". 

The other commits add more verbose assertion messages and change the encoding of dram_block_size_bytes from bytes to octets to enable bigger workloads.

2019-10-13 21:56 UTC, maltanar requested changes
1)  The test suite in the hardware-software cosimulation (PLATFORM=VerilatedTester make emu) does not currently pass when I try it with this branch; last output from the terminal is

`Starting test: binary_onchip_onetile_ktile1
binary_onchip_onetile_ktile1: 2x64x2 1bx1b signed? 0 0`

Can you re-check this, and also mention which version of Vivado you are using? For me both 2017.4 and 2019.1 had the same problem.

2) I suggest to change the name of the field `dram_block_size_bytes` to `dram_block_size_qword`, in both the Chisel/Scala and Vivado HLS sources that make use of this field, as the unit has changed from bytes to 8-bytes (note that octet normally refers to eight bits and not eight bytes, qword seems to be the closest thing to a convention for this: https://en.wikipedia.org/wiki/Word_(computer_architecture)#Size_families)

2019-10-14 19:45 UTC, kathjo commented
I had ordered one of the bit-shift operations incorrectly, issue with smaller DPA dimensions should be fixed now. Also included requested variable name change.

2019-10-18 15:43 UTC, maltanar approved these changes

2019-10-18 15:43 UTC, merged

2019-10-18 15:44 UTC, maltanar commented
I've re-run VerilatedTester emulation for several different array sizes as well as a hardware test on the Ultra96, and all looks good. Thanks for your contribution.